# Generated by Django 6.0 on 2025-12-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
